# Generated by Django 2.2.7 on 2020-01-29 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_auto_20200129_1043'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='cat',
            new_name='category',
        ),
        migrations.CreateModel(
            name='item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ItemName', models.TextField()),
                ('itemcat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.category')),
            ],
        ),
    ]
